


# Permalinks
permalink:        pretty

# Setup
title:            Holy Cross Manuscripts Hackathon
tagline:          'February, 2018'
description:      'One-day collaborative hackathon to produce a digital diplomatic edition of the bestiary known as the "Bern Physiologus" (Bern Codex 318).'


baseurl: '/ms-hackathon-2018/'


author:
  name:           'Neel Smith'


links:
  - title: HCMID home
    url: http://hcmid.github.io/
    external: true
